// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WebDataLayer.DBMS
{
    public partial class Device
    {
        public Device()
        {
            DeviceArk = new HashSet<DeviceArk>();
            DeviceInformation = new HashSet<DeviceInformation>();
        }

        public string DeviceId { get; set; }
        public string LicenseId { get; set; }
        public string Part1 { get; set; }
        public string Part2 { get; set; }
        public string Part3 { get; set; }
        public string Part4 { get; set; }
        public string Part5 { get; set; }
        public string Part6 { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? DisabledDate { get; set; }
        public string Name { get; set; }

        public virtual License License { get; set; }
        public virtual ICollection<DeviceArk> DeviceArk { get; set; }
        public virtual ICollection<DeviceInformation> DeviceInformation { get; set; }
    }
}