// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WebDataLayer.DBMS
{
    public partial class DeviceInformation
    {
        public Guid DeviceInformationId { get; set; }
        public string DeviceId { get; set; }
        public string InformationName { get; set; }
        public string InformationValue { get; set; }
        public DateTime? ValidDate { get; set; }
        public string InformationType { get; set; }
        public string InformationCategory { get; set; }

        public virtual Device Device { get; set; }
    }
}