// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WebDataLayer.DBMS
{
    public partial class DeviceArk
    {
        public string ArkId { get; set; }
        public string DeviceId { get; set; }
        public string ArkName { get; set; }
        public int? TotalGbSize { get; set; }
        public int? TotalGbFileCount { get; set; }
        public DateTime? DisabledDate { get; set; }
        public DateTime? TotalUpdateDate { get; set; }

        public virtual Device Device { get; set; }
    }
}