// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WebDataLayer.DBMS
{
    public partial class License
    {
        public License()
        {
            Device = new HashSet<Device>();
            OptIn = new HashSet<OptIn>();
        }

        public string LicenseId { get; set; }
        public string Email { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public bool? EmailSent { get; set; }
        public bool? EmailConfirmed { get; set; }
        public DateTime? LicensePaidDate { get; set; }
        public string PhoneNumber { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public int? MaxArksSupported { get; set; }
        public int? MaxDevicesSupported { get; set; }
        public int? MaxGbAllArk { get; set; }
        public int? MaxGbFilesSingleArk { get; set; }
        public int? MaxViolations { get; set; }
        public int? MaxGbSingleArk { get; set; }

        public virtual ICollection<Device> Device { get; set; }
        public virtual ICollection<OptIn> OptIn { get; set; }
    }
}